typography_spectrum: 0
color:
  saturation: 1
  brandStrength: 0.152795372530818
  lightness: 1
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
author:
  name: In Vino Momentum | Jurgen Retra
  email: info@invinomomentum.nl
  url: thegrid.ai/invinomomentum
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/47506852-bb22-4baf-b301-9f61188fc049.jpg
name: In Vino Momentum
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: Old site
    url: 'http://www.invinomomentum.nl'
    type: external
  - name: Facebook
    url: 'https://www.facebook.com/InVinoMomentum/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a73a8152-aa4d-48fb-82ab-c1d3f3a7a506.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
